/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_Kontroler */

#ifndef _Included_application_Kontroler
#define _Included_application_Kontroler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_Kontroler
 * Method:    funkcija
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_application_Kontroler_funkcija
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
